
{{- if .Values.backup_v2.enabled }}
kind: Ingress
{{- if .Capabilities.APIVersions.Has "apps/v1" }}
apiVersion: apps/v1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}

metadata:
    annotations:
      vice-president: "true"
    name:  {{ include "fullName" . }}-backup

spec:
  rules:
    - host:  {{ .Values.name }}.mariabackup.{{ .Values.global.region }}.cloud.sap
      http:
        paths:
          - path: /
            backend:
              serviceName:   {{ include "fullName" . }}-backup
              servicePort: 8081
  tls:
    - hosts:
      -  {{ .Values.name }}.mariabackup.{{ .Values.global.region }}.cloud.sap
      secretName: tls-{{ .Values.name }}-mariabackup-{{ .Values.global.region }}-cloud-sap
{{- end }}
