kind: Ingress
{{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}

metadata:
  name: nova-console
  labels:
    system: openstack
    type: backend
    component: nova
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    {{- if .Values.vice_president }}
    vice-president: "true"
    {{- end }}
spec:
  tls:
  - secretName: tls-{{include "nova_console_endpoint_host_public" . | replace "." "-" }}
    hosts: [{{include "nova_console_endpoint_host_public" .}}]
  rules:
  - host: {{include "nova_console_endpoint_host_public" .}}
    http:
      paths:
      {{- range $name, $config := .Values.consoles }}
      - path: /{{ $name }}
        backend:
          serviceName: nova-console-{{ $name }}
          servicePort: {{ $name }}
      {{- end }}

{{ $envAll := . }}
{{- range $name, $config := .Values.consoles }}
---
{{ tuple $envAll $name $config | include "nova.console_service"  }}
{{- end }}
