kind: Ingress
{{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}

metadata:
  name: nova-placement-api
  labels:
    system: openstack
    type: api
    component: nova
  {{- if .Values.vice_president }}
  annotations:
    vice-president: "true"
  {{- end }}
spec:
  tls:
     - secretName: tls-{{include "placement_api_endpoint_host_public" . | replace "." "-" }}
       hosts: [{{include "placement_api_endpoint_host_public" .}}]
  rules:
    - host: {{include "placement_api_endpoint_host_public" .}}
      http:
        paths:
        - path: /
          backend:
            serviceName: nova-placement-api
            servicePort: {{.Values.global.placementApiPortInternal}}
