apiVersion: "openstack.stable.sap.cc/v1"
kind: "OpenstackSeed"
metadata:
  name: glance-seed
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  requires:
  - {{ default .Release.Namespace .Values.global.keystoneNamespace }}/keystone-seed
  - domain-default-seed
  - domain-ccadmin-seed
{{- if .Values.tempest.enabled }}
  - monsoon3/domain-tempest-seed
{{- end }}
  - swift/swift-seed

  roles:
  - name: cloud_image_admin
  - name: image_admin

  services:
  - name: glance
    type: image
    description: Openstack Image
    endpoints:
    - interface: admin
      region: {{ .Values.global.region | quote }}
      url: http://{{include "glance_api_endpoint_host_admin" .}}:{{.Values.api_port_internal}}
    - interface: public
      region: {{ .Values.global.region | quote }}
      url: https://{{include "glance_api_endpoint_host_public" .}}
    - interface: internal
      region: {{ .Values.global.region | quote }}
      url: http://{{include "glance_api_endpoint_host_internal" .}}:{{.Values.api_port_internal}}

  domains:
  - name: Default
    users:
    - name: admin
      role_assignments:
      - domain: Default
        role: cloud_image_admin
      - project: admin
        role: cloud_image_admin
    - name: glance
      description: 'Glance Service'
      password: '{{.Values.global.glance_service_password}}'
      role_assignments:
      - project: service
        role: service
    groups:
    - name: administrators
      role_assignments:
      - domain: Default
        role: cloud_image_admin
      - project: admin
        role: cloud_image_admin

  - name: ccadmin
    projects:
    - name: master
      role_assignments:
      - user: image-build@Default
        role: cloud_image_admin
      - user: glance@Default
        role: swiftoperator
    - name: BaremetalMonitoring
      description: 'Appliances used for monitoring bare metal servers'
      role_assignments:
      - user: image-build@Default
        role: cloud_image_admin
    groups:
    - name: CCADMIN_CLOUD_ADMINS
      role_assignments:
      - project: master
        role: cloud_image_admin
      - project: cloud_admin
        role: cloud_image_admin
    - name: CCADMIN_API_SUPPORT
      role_assignments:
      - project: api_support
        role: image_admin
      - project: api_tools
        role: image_admin
    - name: CCADMIN_COMPUTE_SUPPORT
      role_assignments:
      - project: compute_support
        role: image_admin
      - project: compute_tools
        role: image_admin
    - name: CCADMIN_NETWORK_SUPPORT
      role_assignments:
      - project: network_support
        role: image_admin
      - project: network_tools
        role: image_admin
    - name: CCADMIN_STORAGE_SUPPORT
      role_assignments:
      - project: storage_support
        role: image_admin
      - project: storage_tools
        role: image_admin
    - name: CCADMIN_SERVICE_DESK
      role_assignments:
      - project: service_desk
        role: image_admin

  - name: bs
    groups:
    - name: BS_API_SUPPORT
      role_assignments:
      - project: api_support
        role: image_admin
    - name: BS_COMPUTE_SUPPORT
      role_assignments:
      - project: compute_support
        role: image_admin
    - name: BS_NETWORK_SUPPORT
      role_assignments:
      - project: network_support
        role: image_admin
    - name: BS_STORAGE_SUPPORT
      role_assignments:
      - project: storage_support
        role: image_admin
    - name: BS_SERVICE_DESK
      role_assignments:
      - project: service_desk
        role: image_admin

  - name: fsn
    groups:
    - name: FSN_API_SUPPORT
      role_assignments:
      - project: api_support
        role: image_admin
    - name: FSN_COMPUTE_SUPPORT
      role_assignments:
      - project: compute_support
        role: image_admin
    - name: FSN_NETWORK_SUPPORT
      role_assignments:
      - project: network_support
        role: image_admin
    - name: FSN_STORAGE_SUPPORT
      role_assignments:
      - project: storage_support
        role: image_admin
    - name: FSN_SERVICE_DESK
      role_assignments:
      - project: service_desk
        role: image_admin

  - name: hcm
    groups:
    - name: HCM_API_SUPPORT
      role_assignments:
      - project: api_support
        role: image_admin
    - name: HCM_COMPUTE_SUPPORT
      role_assignments:
      - project: compute_support
        role: image_admin
    - name: HCM_NETWORK_SUPPORT
      role_assignments:
      - project: network_support
        role: image_admin
    - name: HCM_STORAGE_SUPPORT
      role_assignments:
      - project: storage_support
        role: image_admin
    - name: HCM_SERVICE_DESK
      role_assignments:
      - project: service_desk
        role: image_admin

  - name: hcp03
    groups:
    - name: HCP03_API_SUPPORT
      role_assignments:
      - project: api_support
        role: image_admin
    - name: HCP03_COMPUTE_SUPPORT
      role_assignments:
      - project: compute_support
        role: image_admin
    - name: HCP03_NETWORK_SUPPORT
      role_assignments:
      - project: network_support
        role: image_admin
    - name: HCP03_STORAGE_SUPPORT
      role_assignments:
      - project: storage_support
        role: image_admin
    - name: HCP03_SERVICE_DESK
      role_assignments:
      - project: service_desk
        role: image_admin

  - name: hec
    groups:
    - name: HEC_API_SUPPORT
      role_assignments:
      - project: api_support
        role: image_admin
    - name: HEC_COMPUTE_SUPPORT
      role_assignments:
      - project: compute_support
        role: image_admin
    - name: HEC_NETWORK_SUPPORT
      role_assignments:
      - project: network_support
        role: image_admin
    - name: HEC_STORAGE_SUPPORT
      role_assignments:
      - project: storage_support
        role: image_admin
    - name: HEC_SERVICE_DESK
      role_assignments:
      - project: service_desk
        role: image_admin

  - name: monsoon3
    groups:
    - name: MONSOON3_DOMAIN_ADMINS
      role_assignments:
      - project: cc-demo
        role: image_admin
    - name: MONSOON3_API_SUPPORT
      role_assignments:
      - project: api_support
        role: image_admin
    - name: MONSOON3_COMPUTE_SUPPORT
      role_assignments:
      - project: compute_support
        role: image_admin
    - name: MONSOON3_NETWORK_SUPPORT
      role_assignments:
      - project: network_support
        role: image_admin
    - name: MONSOON3_STORAGE_SUPPORT
      role_assignments:
      - project: storage_support
        role: image_admin
    - name: MONSOON3_SERVICE_DESK
      role_assignments:
      - project: service_desk
        role: image_admin

  - name: s4
    groups:
    - name: S4_API_SUPPORT
      role_assignments:
      - project: api_support
        role: image_admin
    - name: S4_COMPUTE_SUPPORT
      role_assignments:
      - project: compute_support
        role: image_admin
    - name: S4_NETWORK_SUPPORT
      role_assignments:
      - project: network_support
        role: image_admin
    - name: S4_STORAGE_SUPPORT
      role_assignments:
      - project: storage_support
        role: image_admin
    - name: S4_SERVICE_DESK
      role_assignments:
      - project: service_desk
        role: image_admin

  - name: wbs
    groups:
    - name: WBS_API_SUPPORT
      role_assignments:
      - project: api_support
        role: image_admin
    - name: WBS_COMPUTE_SUPPORT
      role_assignments:
      - project: compute_support
        role: image_admin
    - name: WBS_NETWORK_SUPPORT
      role_assignments:
      - project: network_support
        role: image_admin
    - name: WBS_STORAGE_SUPPORT
      role_assignments:
      - project: storage_support
        role: image_admin
    - name: WBS_SERVICE_DESK
      role_assignments:
      - project: service_desk
        role: image_admin

{{- if .Values.tempest.enabled }}
  - name: tempest
    projects:
    - name: admin
      role_assignments:
        - user: admin
          role: cloud_image_admin
        - user: admin@Default
          role: cloud_image_admin
    - name: tempest1
      role_assignments:
        - user: admin@Default
          role: cloud_image_admin
    - name: tempest2
      role_assignments:
        - user: admin@Default
          role: cloud_image_admin
{{- end }}
