dependencies:
  - name: elasticsearch
    alias: elasticsearch
    version: 7.6.1
    repository: file://vendor/helm-charts/elasticsearch

  - name: kibana
    repository: file://vendor/helm-charts/kibana
    version: 7.6.1

  - name: logstash
    repository: file://vendor/helm-charts/logstash
    version: 7.6.1
